# netlify.toml
[build]
  command = "npm --prefix frontend run build"
  publish = "frontend/out"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
